### ISSUE TITLE
P1 smart meter reports total gas usage as current gas usage

### ISSUE THREAD

**Issue by pro-sumer** [koktaildotcom/com.p1.smartmeter#7] opened 2019-04-23 15:18 UTC
While the reported current and total gas usage have been fine at first, the "P1 smart meter" App recently started reporting the total gas usage as the current gas usage (but with more digits, less rounding: 3 digits for current, 2 digits for total).

Example: current = xxxx.755 m3, total = xxxx.76 m3 (with the same digits for `xxxx` for both)

I'm not sure whether it's the Homey App or the Node P1 Reader script that's causing this.

**Comment by koktaildotcom** [comment] 2019-12-20 06:11
Is thuis fixed with the new script that pushes data to Homey?

**Comment by pro-sumer** [comment] 2019-12-21 18:42
Did not reproduce in the few minutes that I tried the new script.

However, for longtime usage I need to decide whether to update my fork (with separate devices for power and gas, which I prefer) or return to your App/script.

**Comment by koktaildotcom** [comment] 2020-01-02 19:17
The issue is resolved. In the new device you can chose if you have gas or not

**Closed** 2020-01-02 19:17 UTC
Labels: bug
